language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer selfupdate
  - composer install --prefer-source

script:
  - bin/phpunit
  - bin/coke

matrix:
  allow_failures:
    - php: 7